require 'active_support/all'

require 'graphql_client/base.rb'
require 'graphql_client/field.rb'
require 'graphql_client/request.rb'
require 'graphql_client/connection_proxy.rb'
require 'graphql_client/response.rb'
require 'graphql_client/schema.rb'
require 'graphql_client/type.rb'
require 'graphql_client/query_builder.rb'
require 'graphql_client/object_proxy.rb'
require 'graphql_client/connection_query.rb'
require 'graphql_client/list_proxy.rb'
require 'graphql_client/list_query.rb'
require 'graphql_client/argument.rb'
